crosire/reshade-shaders

ReShade/McFX/DOF.fx

It only worked for autofocus. Should work now for manual focus too.

Fix the near DOF curve control.

---

ReShade/Otis/Common.fx

Small correction in pragma credits text and common.fx.

Corrected credits in OtisFX

---

ReShade/Shaders/Ganossa/UIMask.fx

`ReShade/Profiles/__APPLICATION_NAME__/Textures/uiMask.png`

feat(profile): add load profile Textures/uiMask.png

---

Shaders/LightDoF.fx

Is this the proper way to do a pull request? Sorry I'm new to this.
Made a thread here http://reshade.me/forum/shader-presentation/2297-light-dof-for-reshade-3-0
This is a simple-but-sleek depth of field shader

Added light dof

---

Shaders/ReflectiveBumpmapping.fx

Finally an updated and more versatile version of this.

Adding the totally revamped RBM

---

Shaders/AdaptiveFog.fx

Adaptive Fog port to reshade v3 format

Adaptive Fog port to reshade v3 format

---

Shaders/PerfectPerspective.fx

Lens distortion effect. Transforms linear perspective, to stereographic.

Perfect Perspection effect

---

Shaders/Chromakey.fx
Shaders/FilmicAnamorphSharpen.fx

Fixed issue with depth preprocessor settings

Hotfix for FilmicAnamorphSharpen and Chromakey

---

Shaders/FilmicAnamorphSharpen.fx
Shaders/PerfectPerspective.fx
Shaders/Prism.fx

Added "ui_category" from the new functionality in ReShade 3.2.2

Update shaders for 3.2.2 ReShade functionality

---

Shaders/Prism.fx

Now the effect does not distort the image.

Updated Prism.fx

---

Shaders/PerfectPerspective.fx

Updated PerfectPerspective.fx

---

Shaders/Depth3D.fx

Tool Tips changes to try to explain what functions do in UI do a little better.
Category corrections.
Code:  zBuffer NearestScaled used to scale/separate in world weapon hand has been adjusted to work on a greater amount of games. Code compression and code fixes. Also had to adjust the scale.
The corrections allow for proper weapon hand handling in most games. Without affecting world scaling.
Image of proper Weapon Hand Scaling.
https://cdn.discordapp.com/attachments/305472403977404416/476856416867450885/unknown.png

Depth3D Tool Tips, Category,  & Code changes

---

Shaders/PerfectPerspective.fx

Added line breaks to the tooltip section, plus some additional info

Update for PerfectPerspective.fx tooltip section

---

Shaders/HSLShift.fx

HSL Shift Shader by kingeric1992

Added HSL Shift

---

Shaders/CinematicDOF.fx

- Optimizations across the board, no more if statements in tight loops. 
- Highlight tweaking/fix so bright centers are avoided in certain blur scenarios
- Better tooltips so users are helped better what does what.

CinematicDOF: optimizations, tweaks, better tooltips

---

Shaders/DisplayDepth.fx
Shaders/Monochrome.fx
Shaders/Nostalgia.fx

DisplayDepth now has dithering and looks much smoother

Added dithering to DisplayDepth

---

Shaders/PerfectPerspective.fx

Fixed issue with inaccurate debug view at high FOV settings (170), where result circle would get octagonal shape

Update to PerfectPerspective.fx debug view

---

Shaders/CinematicDOF.fx

See: https://reshade.me/forum/shader-presentation/4535-new-shader-cinematic-depth-of-field?start=40#29504
The autofocus code doesn't work in direct3d9 when called from a vertex shader. As there were already ifdef's in place for reshade versions 3.4 and earlier, I adjusted them to now also use the pixelshader route for focusing data calculation in direct3d9. It is what it is...

Cinematic DOF: Auto-focus doesn't work in a vertex shader in dx9

---

Shaders/Depth3D.fx

Depth Buffer Linearization Changed
+Offset Added
AverageLuminance Pass moved so that it does not freeze up in DX9 games.
Convergence code simplified.
Occlusion Masking Power Adjusted
Disocclusion Code Changed.
Encode Now handles added  depth buffer adjusments. Should give a better image overall for both eyes.
Code enhancements from SuperDepth3D_FB added.
Depth Map Division Now Default to 1.75
Divergence code change to match SuperDepth3D_FB code.

Depth3D Update & Fixes

---

Shaders/Depth3D.fx

Depth3D
+Added a simple byte shift for de-banding in the final 3D image.
+Made more controls automatic like Disocclusion Power Adjust.
+Added more information in the shader.
+Interlace Optimization removed and set to a default of in shader 50%
+Depth Map View set to color mode from quad panel mode.
Merged some menus
+Anaglyph Colors now merged with Stereoscopic Mode.
Description change
+ZPD is now Convergence in the hope of making it easier to understand.
The goal is to make it easier for the end-user to use the shader.

Depth3D Update

---

Shaders/PerfectPerspective.fx

• Changed labeling, hopefully it will now clear some confusion of what this shader does
• Changed order of the settings to more logical
• Added more descriptive tooltips
• Changed some default values, for better experience of new users

Update labeling to PerfectPerspective.fx

---

Shaders/CinematicDOF.fx

Tile gatherer should collect min CoC not average of min CoC: now ends of narrow lines are properly handled too. This also fixes white dot flickering near edges in near plane in some TAA using games due to depth buffer jitter.
I couldn't find the cause of this and it drove me mad, finally saw what's wrong :) 
The previous version (the one in the main repo) caused all kinds of flickering white dots around the edges of the elements in the near plane, ruining the point of blurring it in the first place as they made it look quite ugly. Only happened in some games tho. (In AC:Odyssey with TAA it was very prominent, however in my test environment with UE4 test demos with TAA they didn't show up). The pointy edges now also properly get a soft edge which was less prominent in the version in the …

CinematicDOF: Near plane bugfix

---

Shaders/DisplayDepth.fx

Changed to variable name from iUILogArithmic to iUILogarithmic

---

Shaders/CinematicDOF.fx

Removed averaging pass for CoC values as it resulted in noticeable wrong CoC values around edges in some TAA using games. The net result was minimal anyway and the downside of it was severe in some games. It wasn't noticeable in my test environment (UE4 demo app) but was very noticeable in Shadow Warrior 2 for instance, where TAA is implemented but the jitter of the depth buffer is minimal.

Updated CinematicDOF: Removed averaging pass for CoC values 

---

Shaders/Macros.fxh

First release. Example UI file can be found on the forum: [Here](https://reshade.me/forum/shader-presentation/4538-ui-texture-sampler-and-technique-macros#29161)

UI, Texture, Sampler, Technique, and Pass Macros

---

Shaders/DOF.fx

https://reshade.me/forum/general-discussion/5106-for-loop-issue-when-int-type-condition-in-d3d9

Quick fix that for-loop issue in D3D9

---

Shaders/CinematicDOF.fx

Updated the CinematicDOF to v1.1.8.
Changes:
* v1.1.8: Added anamorphic bokeh support, so bokehs now get stretched and rotated based on the distance from the center of the screen, with various tweaks. (of course the normal circular bokehs are the default)
* v1.1.7: Added 9-tap tent filter as described in [Jimenez2014] for mitigating undersampling. Implementation is from KinoBokeh (see credits in file).
* v1.1.6: When near plane max blur is set to 0, the original fragment is now used in the near plane instead of the half-res pixel. 
* v1.1.5: Added far plane highlight normalizing for non-gained highlights. Added tooltip for reshade v4.x
* v1.1.4: Far plane weight calculation tweaked a bit as near-focus plane elements could lead to hard edges which looked ugly. Highlight far plane …

Updated cinematicDOF to v1.1.8

---

Shaders/Chromakey.fx
Shaders/FilmicAnamorphSharpen.fx
Shaders/PerfectPerspective.fx
Shaders/Prism.fx
Shaders/TiltShift.fx

Update shaders for ReShade 4.2

---

Shaders/PPFX_SSDO.fx

Incorrect texture was specified after the additive fixes.

Fix PPFX_SSDO.fx Regression

---

Shaders/CinematicDOF.fx

- Rewritten / clean up of highlight pipeline, removal of redundant controls
- New weight calculation for far plane
- Near plane alpha optimization
New highlights look like this:
They look like that out of the box, no more fiddling with a myriad of controls. Also changed the edge weights to a 'busy bokeh' control to make it more life-like in situations where you e.g. have a lot of tree branches in the background.

Cinematic DOF v1.1.13

---

Shaders/AspectRatio.fx
Shaders/FilmicAnamorphSharpen.fx
Shaders/PerfectPerspective.fx

Added radial mask option and changed some labels and settings order.

Update FilmicAnamorphSharpen.fx, add AspectRatio.fx

---

Shaders/DrawText.fxh

Update DrawText.fxh per request by discord user crabshank

accomadate float division error.

---

Shaders/PPFX_SSDO.fx

PPFX SSDO Change to use standard Reshade.fxh Preprocessors

---

Shaders/AdaptiveFog.fx
Shaders/AdaptiveSharpen.fx
Shaders/Clarity.fx
Shaders/Depth3D.fx
Shaders/DepthHaze.fx
Shaders/GaussianBlur.fx
Shaders/LightDoF.fx
Shaders/LumaSharpen.fx
Shaders/MagicBloom.fx
Shaders/PPFX_Bloom.fx
Shaders/PPFX_Godrays.fx
Shaders/PPFX_SSDO.fx
Shaders/SMAA.fx
Shaders/SurfaceBlur.fx
Shaders/TiltShift.fx

I've tried to be careful about not marking the wrong ones.

Marking textures as pooled

---

Shaders/AdaptiveFog.fx
Shaders/Colourfulness.fx
Shaders/DepthHaze.fx
Shaders/DisplayDepth.fx
Shaders/Emphasize.fx
Shaders/MultiLUT.fx
Shaders/StageDepth.fx

Just Linux things :frog: 
I hope I found them all.

Use proper capitalization of files names

---

Shaders/UIMask.fx

It was reported in the Discord server that the effect was broken, I ended up fixing it through some refactoring.

Fixed UIMask

---

ShadersAndTextures/Flair.fx
ShadersAndTextures/Particles.fx

Flair.fx is a "Lens Flare" based shader that can use depth to assist in the application of the flares.
Not all lens flare system is emulated by this shader. Some other flares can and may be added later.
This shader was made for Nvidia Freestyle system and can also be used in normal ReShade. 
I am also uploading this shader because I wanted to keep this archive a bit fresh. 
Thank you, Handpunk for support.
Thank you, crosire for making this possible and are you sure we don't capitalize your name? :smile:

Adding one shader to the Nvidia Shader Pool.

---

Shaders/DisplayDepth.fx

This change ask users to try reversing depth if they see normals but the depth view is black.

Improve help text

---

Shaders/TriDither.fxh

No worries if you don't feel this is needed on the slim branch.

Add TriDither to Slim branch

---

Shaders/TriDither.fxh

Just multiplying the timer by 0.001

Fix dither timer not actually animating.
