ReShade/JPulowski.cfg, ReShade/JPulowski.undef, ReShade/JPulowski/AdaptiveSharpen.fx
The first pass now passes edge and luma data in a RG16F texture.
Added a fast code path "fast_ops" that is enabled by default and gives a
very small perceptual differance and a good speedup.
Rendering time differences (effect on - off) with a AMD7790@1080p:
1.2                   - 3.2ms
1.2a, fastops 0 - 2.5ms  ~28% speedup
1.2a, fastops 1 - 2.2ms  ~45% speedup
=> Speed optimizations for adaptive sharpen

ReShade/Presets/Default/Otis.cfg, ReShade/Shaders/Otis.undef, ReShade/Shaders/Otis/DepthHaze.fx
I added a fog feature to the DepthHaze shader so it's now possible to add depth based fog (around the center of the screen). So it's not adding fog simply based on depth, it is more pronounced around the center line of the screen (to avoid fogged skies which look awful ;)) See: http://imgur.com/et18C7B&IwKr2kG&U1R1Kwh&sg5c5JA for examples. 
I hope I have done everything correctly. I can't test it as I don't have the v2.0 reshade dll. If I have to adjust a setting or something, please let me know :) This also addresses: http://reshade.me/forum/releases/1381-1-1?start=60#12765
=> Updated Otis/DepthHaze effect with fog 

ReShade/Shaders/MartyMcFly/DOF.fx
Moved mouse driven focus point calculation outside loop as it's constant for each iteration. It was calculated with each iteration, which isn't correct. It's not a big deal, but every cycle counts ;)
=> Small optimization in DoF: 

ReShade/Shaders/Ganossa/UIMask.fx
`ReShade/Shaders/Ganossa/UIMask.fx(51, 35): error X3011: value must be a literal expression`
http://reshade.me/forum/shader-troubleshooting/1964-uimask-error
=> fix(error): uiMask int value

Shaders/LumaSharpen.fx
The default pattern should be "normal" not "wider". According to new
scheme pattern should be set to 1, not 2 which was the case in the
previous scheme.
=> Changed default pattern for LumaSharpen

Shaders/FakeHDR.fx
When debugging someone's glsl port of FakeHDR, found that the blur in it is returning weird result
// unedited:
The coordinates offsets seem to be unnormalized, I thought Reshade takes unnormalized coordinates, so I looked into some other shaders that also does blur, but it seems they all use normalized coordinates.
// after edit:
=> Normalize the offsets in FakeHDR shader

Shaders/PerfectPerspective.fx
I've made small mistake in calculations with correction formula.
There's no difference for 90 degrees FOV since Ctand(45) is equal 1, but for higher and lower FOV it was showing wrong result.
Now I triple checked it.
=> Precision optimization for PerfectPerspective.fx

Shaders/PerfectPerspective.fx
Added setting to choose between horizontal/vertical/diagonal in-game FOV. No need to use FOV calculator if game uses non-horizontal FOV settings. Plus some minor label changes for more descriptive informations.
=> Update to PerfectPerspective.fx

Shaders/PerfectPerspective.fx
New 2.0 version of PerfectPerspective.
It now uses proper stereographic-gnomonic lookup formula.
Previous version was now showing exact stereographic perspective.
No distortion scaling option, it was producing wrong effect.
=> Update PerfectPerspective.fx to 2.0

Shaders/PerfectPerspective.fx
Reduced instruction slots used in PerfectPerspective (tested in GPU ShaderAnalyzer 1.59).
13 instruction slots from 16 previously.
=> Updated PerfectPerspective.fx

Shaders/CRT.fx
This reverts a2d6146c943960596c800ceba6b13edc492f87e7 and fixes the amount option.
Instead of interpolating between the raw original image and the _finished_ scanlined image the shader now interpolates between the transformed original image and the scanlined image.
This way the `Amount` option works in conjunction with the `Curvature` and the `CornerSize` option.
=> Re-add amount option to CRT shader and fix it

Shaders/Emphasize.fx
Enhances Emphasize shader with a 3D component so it now allows to specify a sphere instead of a 2D plane (both options are still available). Enhancement by SirCobra, who asked me to commit this change to the main repo. (his words: The zone can now be calculated on the distance of a pixel to a focus-point in it's estimated 3D environment.) 
Looks something like this:  
:smiley:
=> Enhances Emphasize shader with a 3D component

Shaders/Depth3D.fx
Depth3D is a zBuffer based stereoscopic post-process shader.
Allows for Side By Side, Top & Bottom, Line Interlaced, and Anaglyph 3D output options.
=> Depth3D Stereoscopic Shader

Shaders/CinematicDOF.fx
The bokeh highlights are much better now:
- no more errors around edges where the depth buffer doesn't align with framebuffer (happens in some UE3 games I've seen)
- allows for 'busy' bokeh where you can create highlights with a slighter brigher edge than the center
- better control over highlight brightness (separated near/far plane)
Also increased manual focus range in the slider to 150 max. (was 100). 
Example:
=> CinematicDOF: Much better bokeh highlighting, better control over highlights, larger range for manual focus

Shaders/CinematicDOF.fx
Made several improvements to the Cinematic DOF shader:
- Much better near-plane bleed: 
- Corrected an issue with the post-gaussian blur bleeding near focus pixels
- Optimized things across the board
- Corrected near-plane highlight bleed. 
- Corrected comments, removed reference of info no longer used.
=> Updated Cinematic DOF shader

Shaders/CinematicDOF.fx
Updated Cinematic DoF.
-   Now using half-res for better performance (5 rings, no undersampling artifacts, 1.89ms @ 1200p in the scenes below. It of course varies how much performance it takes, very busy / high poly scenes might take a bit more, till e.g. 3ms)
-   New highlight implementation to keep highlight bokeh, and optional old one still available
-   Better near plane bleed which deals properly with e.g. branches and edges
-   Auto-focus transition delay
-   Better weight for far plane so DoF is now more evenly applied in far plane, avoiding ugly edges around e.g. leafs
-   Lots of small optimizations and tweaks.
It looks like this: 
(highlights)
(near plane bleed with edges)
I squashed all commits I made, as it was a lot of work to get things right and a lot of commits are no …
=> Updated Cinematic DoF

Shaders/AdaptiveFog.fx, Shaders/CinematicDOF.fx
One pr with bugfixes for 2 shaders
Adaptive Fog: fogstart now actually does what it should. Controls are now much easier to use as well. (as in: they're usable now)
Cinematic DOF: 
- Near plane blur is now resolution independent 
- Small tweak in luma constant usage (less constructor calls), pre-blur luma weight adjustment for out-of-focus areas
- Fixes bug in highlight bleeding due to pre-blur not masking enough.
- Small tweak in pre blur to mitigate highlight bleed in near-focus areas
- Average CoC calculation forgot central pixel 
- Combiner now uses full res for far plane if far plane blur is set to 0 so you can create screenshots with just near plane blur.
=> Bug fixes in CinematiC DOF and Adaptive Fog

Shaders/PerfectPerspective.fx
Changed DSR scale factor to Int2 for ease of use.
• DSR scale factor actual number can be seen only in Nvidia Control Panel, not in game
• previous setting did not reflect that value since DSR Nvidia value is not resolution scale, but pixel count (end result is x2)
• to previously get proper value for that setting, user had to manually divide DSR resolution by native screen resolution (like 2560/1920≈1.3333)
Now the setting does that for you, just type in the first box your native screen resolution (either vertical or horizontal) and in the second, one that your game runs on.
=> Updated Prefect Perspective debug tools

Shaders/DisplayDepth.fx
- Removed labels of iUIUpsideDown, iUIReversed, iUILogarithmic as they were redundant with the content of the combo box
- Added checking of the depth map in the technique tooltip due to the fixed normals calculation. When RESHADE_DEPTH_INPUT_IS_REVERSED is set wrong you still see the normals but differently colored.
- Updated the uniform for switching between normal map and depth map
Is it actually necessary to have the far plane value tweakable in the shader? I must admit, I've never touched that value even once in the preprocessor settings. If having that is useless I think we should remove it.
=> Updated uniforms & technique tooltip

Shaders/DisplayDepth.fx
At the ReShade version reached 4.0, DisplayDepth has updated of setting method the preprocessor.
But some users misunderstand the depth preview because there are not leaned what about the correct display results of normal map.
This request contain that changes to display a preview of depth maps on each of split screen areas.
For users, do edit the settings until both depth effects are displayed on the each screen areas.
Add a new present type "Show both(Vertical 50/50)"
Not effective
Preprocessor settings is wrong (_REVERSED)
Preprocessor settings is correct
=> Add a new depth present type "Show both"

Shaders/PerfectPerspective.fx
Major update to Perfect Perspective:
• Adds new projection type for various use-cases
• Removed bug in ReShade 4.x where borders color was displayed as a vector
• Changed some tooltips
• Added Slider UI option with backward compatibility
• Various small changes
PS:
Changed line-end symbol to Windows, same as in ReShade 4.x code editor.
To see only changed code there's option "Hide white-space changes" somewhere.
=> Update to Perfect Perspective

Shaders/DisplayDepth.fx, Shaders/FilmicAnamorphSharpen.fx
• Fixed bug with flipped 601 and 709 luma values
• Fixed undeclared value before loop "add"
• Added mask switch so that performance with disabled depth mask is the same as in regular FilmicSharpen.fx
=> Update FilmicAnamorphSharpen.fx and bugfix DisplayDepth.fx

Shaders/Deband.fx
- Replaced "grain" with CeeJay.dk's ordered dithering algorithm and enabled it by default
- The configuration is now more simpler and straightforward
- Some minor code changes and optimizations
- Improved the algorithm and made it more robust by adding some of the madshi's improvements to flash3kyuu_deband which should cause an increase in quality. Higher iterations/ranges should now yield higher quality debanding without too much decrease in quality.
=> Updated Deband to 2.0

Shaders/SMAA.fx, Shaders/SMAA.fxh
DepthEdgeDetectionThreshold and Predication as a whole were gated behind preprocessor definitions. This had the end result of Edge detection mode being non-configurable from the UI, and the latter being completely unknown or forgotten to even experienced shader developers.
=> Improve SMAA configuration accessibility

Shaders/ReShade.fxh
Sat on resubmitting a pull request for a couple of days pending any feedback from people on discord and as such, this should be good to go for a pull.
Adds the following preprocessors:
RESHADE_DEPTH_MULTIPLIER - Useful for weak emulator buffers. Basically Bolotaur's manual tweak to reshade.fxh (https://reshade.me/forum/general-discussion/5391-release-pcsx2-with-depth-buffer-access) added in as an extra parameter that can vary per profile instead of being per reshade.fxh. When set to 1 it acts exactly the same as before the preprocessor was implemented and is set to that for compatibility by default.
RESHADE_DEPTH_INPUT_X_SCALE and RESHADE_DEPTH_INPUT_Y_SCALE - Used to scale the depth buffer output by. Below 1 shrinks the depth buffer on an axis and above 1 expands the image (2 doubling …
=> Reshade.fxh Emulator Changes

REFERENCE.md
Added "pooled" texture annotation to the reference, as per the ReShade 4.5.0 changelog.
=> Add pooled texture annotation to reference

Shaders/DisplayDepth.fx
Like the other settings from ReShade.fxh the correct offset and scale can now be checked in real-time.
It is possible to blend the depth output with the backbuffer so figuring out the offset is easier.
Also added labels to uniforms and rearragned PS_DisplayDepth a bit.
=> DisplayDepth.fx: add new settings from ReShade.fxh

Shaders/EyeAdaption.fx
Pretty simple addition.  A use case for this variable is positioning the focal point towards the bottom of the screen in third person games to avoid overblooming white sand or snow.
=> Add Y axis focal point variable to EyeAdaption.fx

Shaders/CinematicDOF.fx
- Better near plane alpha calculations so pointy edges are no longer sticking out and edges of softness is now a bit translucent as it should be. 
- fixed issue with near-in focus elements in near plane which weren't blurred particularly well. 
- Changed default of focal length from 120 to 100mm
=> Cinematic DOF v1.1.15.

Shaders/AmbientLight.fx
An updated version of Ganossa's AmbientLight.fx with a toggle to disable dithering and eliminate a pattern of diagonal lines generated by it.
Originally posted by SoZ on the Reshade forums and corrected by me:
[https://reshade.me/forum/shader-presentation/3029-ambientlight-fx-with-dither-toggle#21222](url)
=> Add dither toggle to AmbientLight.fx

REFERENCE.md
The ReshadeFX language is much more similar to HLSL than it is to C++. On GitHub's renfering, the HLSL highlighter is a lot better at picking out keywords for ReshadeFX than the C++ highlighter currently used in the Doc.
=> REFERENCE.md: use HLSL syntax highlighting

Shaders/DisplayDepth.fx
As discussed, this change forces the user to interact with the preprocessor definitions, as users frequently miss the step of transferring the settings. I've used your cleaned version from the slim branch as template, as I presume you'd want this change to be applied to the master branch as well.
=> Lock UI controls behind preprocessor definition at first launch

Shaders/Deband.fx
**3.0:**
- Replaced the entire banding detection algorithm with modified standard deviation and Weber ratio analyses which give more accurate and error-free results compared to the previous algorithm
- Added banding map debug view
- Added and redefined UI categories
- Added depth detection (credits to spiro) which should be useful when banding only occurs in the sky texture for example
- Fixed a bug in random number generation which was causing artifacts on the upper left side of the screen
- Dithering is now applied only when debanding a pixel as it should be which should reduce the overall noise in the final texture
- Minor code optimizations
**3.1:**
- Switched to chroma-based analysis from luma-based analysis which was causing artifacts under some scenarios
- Changed parts of the code …
=> Updated Deband to 3.1
